obeid/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from .views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name="home"),
    path('', include('obeid_projects.urls', namespace='project')),
    path('', include('obeid_tools.urls', namespace='tools')),
    path('tinymce/', include('tinymce.urls')),
]

admin.site.site_header = "Obied Arash"
admin.site.site_title = "Obeid Arash"
admin.site.index_title = "Welcome to Obied Arash Admin Area"

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

obeid_projects/urls.py
from django.urls import path
from .views import ProjectList, project_detail, ProjectCategory, ProjectTag

app_name = 'project'
urlpatterns = [
    path('projects', ProjectList.as_view(), name="list"),
    path('projects/<slug:project_slug>', project_detail, name="detail"),
    path('projects/cat/<slug:category_slug>', ProjectCategory.as_view(), name="category"),
    path('projects/tag/<slug:tag_slug>', ProjectTag.as_view(), name="tag"),
]

obeid_tools/urls.py
from django.urls import path
from .views import youtube

app_name = 'tools'
urlpatterns = [
    path('youtube', youtube, name="youtube"),

]

obeid_projects/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator, EmailValidator
from django.contrib.auth.models import User
from django_countries.fields import CountryField
from tinymce import models as tinymce_models


# from django.db.models.signals import pre_save


class ProjectManager(models.Manager):
    def published_project(self, project_slug):
        qs = self.get_queryset().filter(slug=project_slug, publish=True)
        if qs.count() == 1:
            return qs.first()
        else:
            return None

    def all_published_projects(self):
        return self.get_queryset().filter(publish=True)

    def projects_by_category(self, category):
        return self.get_queryset().filter(category__project__category=category, publish=True).distinct()

    def projects_by_tag(self, tag):
        return self.get_queryset().filter(tag__project__tag=tag, publish=True).distinct()


class Tag(models.Model):
    title = models.CharField(max_length=32)
    slug = models.SlugField(max_length=32, unique=True)
    update = models.DateTimeField(auto_now=True)
    create = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Customer(models.Model):
    name = models.CharField(max_length=64, null=True, blank=True)
    slug = models.SlugField(max_length=128, unique=True, help_text='Name + Lastname')
    lastname = models.CharField(max_length=64, null=True, blank=True)
    email = models.EmailField(null=True, blank=True, validators=[EmailValidator])
    phone = models.CharField(max_length=32, blank=True, null=True)
    country = CountryField(null=True, blank=True)
    update = models.DateTimeField(auto_now=True)
    create = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{} {}".format(self.name, self.lastname)


class Category(models.Model):
    title = models.CharField(max_length=64, unique=True)
    slug = models.SlugField(max_length=64, unique=True)
    update = models.DateTimeField(auto_now=True)
    create = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Categories'


class Project(models.Model):
    title = models.CharField(max_length=256)
    slug = models.SlugField(max_length=256, unique=True)
    content = tinymce_models.HTMLField(null=True, blank=True)
    progress = models.PositiveIntegerField(default=5,
                                           validators=[MinValueValidator(0), MaxValueValidator(100)],
                                           help_text='Pick a number between 0 to 100')
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    category = models.ManyToManyField(Category, blank=True, verbose_name='Categories')
    tag = models.ManyToManyField(Tag, blank=True)
    update = models.DateTimeField(auto_now=True)
    create = models.DateTimeField(auto_now_add=True)
    publish = models.BooleanField(default=True)
    primary = models.BooleanField(default=False)
    objects = ProjectManager()

    def __str__(self):
        return self.title

obeid_tools/models.py
from django.db import models


class Youtube(models.Model):
    url = models.URLField(max_length=256)
    title = models.CharField(max_length=512)
    id = models.CharField(max_length=32, primary_key=True)
    datetime = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

obeid_tools/forms.py
from django import forms
from django.core import validators


class YoutubeForm(forms.Form):
    url = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'https://www.youtube.com/watch?v=LLJhUVkgcvQ',
        'class': 'form-control',
        'value': 'https://www.youtube.com/watch?v=LLJhUVkgcvQ'
    }), required=False, validators=[validators.URLValidator(), ])

obeid/views.py
from django.shortcuts import render
from obeid_projects.models import Project


def home(request):
    latest_projects: Project = Project.objects.filter(publish=True, progress__range=[0, 99]).order_by('-create')[:5]
    completed_projects: Project = Project.objects.filter(progress=100, publish=True).order_by('-update')[:5]
    primary_projects: Project = Project.objects.filter(primary=True).order_by('-update')[:5]
    context = {
        'title': 'Home',
        'latest_projects': latest_projects,
        'completed_projects': completed_projects,
        'primary_projects': primary_projects
    }
    return render(request, 'home.html', context)

obeid_projects/views.py
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView
from .models import Project, Category, Tag


class ProjectTag(ListView):
    # todo: this class must be improve (does not show the good result)
    template_name = 'project/projects.html'
    context_object_name = 'projects'
    paginate_by = 10
    ordering = ['-update']

    def get_queryset(self):
        tag_slug = self.kwargs['tag_slug']
        print(tag_slug)
        tag = Tag.objects.filter(slug=tag_slug).first()
        print(tag)
        if tag is None:
            raise Http404("Tag Does Not Exist")
        else:
            return Project.objects.projects_by_tag(tag)


class ProjectCategory(ListView):
    # todo: this class must be improve (does not show the good result)
    template_name = 'project/projects.html'
    context_object_name = 'projects'
    paginate_by = 10
    ordering = ['-update']

    def get_queryset(self):
        category_slug = self.kwargs['category_slug']
        category = Category.objects.filter(slug=category_slug).first()
        if category is None:
            raise Http404("Category Does Not Exist")
        else:
            return Project.objects.projects_by_category(category)


class ProjectList(ListView):
    model = Project
    queryset = Project.objects.all_published_projects()
    context_object_name = 'projects'
    paginate_by = 10
    ordering = ['-update']
    template_name = 'project/projects.html'


def project_detail(request, project_slug):
    # project = get_object_or_404(Project, slug=project_slug)
    project = Project.objects.published_project(project_slug)
    if project is None:
        raise Http404('Ops!')

    context = {
        'project': project,
    }
    return render(request, 'project/project.html', context)

obeid_tools/views.py
from django.shortcuts import render, Http404
from .forms import YoutubeForm
import pafy
from django.contrib.auth.decorators import login_required
from .models import Youtube


# from pytube import YouTube
# import requests
# from django.http import HttpResponseRedirect


@login_required(login_url='home')
def youtube(request):
    videos = ''
    video = ''
    youtube_form = YoutubeForm(request.POST or None)
    if request.method == "POST" and youtube_form.is_valid():
        url = youtube_form.cleaned_data.get('url')
        try:
            video = pafy.new(url)
        except:
            raise Http404('This is not a youtube url!')
        if video:
            videos = video.videostreams
            youtube_form = YoutubeForm()
            Youtube.objects.create(url=url, title=video.title, id=video.videoid)

    context = {
        'youtube': youtube_form,
        'video': video,
        'videos': videos,
    }
    return render(request, 'tools/youtube.html', context)

templates/home.html
{% extends 'shared/MainReferences.html' %}
{% block description %}I am a web scraper expert who is interested in web Developing{% endblock %}
{% block keywords %}Web Developer, Web Scraper, Data Scraping{% endblock %}
{% block title %}Obeid Arash{% endblock %}
{% block heading %}
    <h1>Obeid Arash Blog</h1>
    <hr>
{% endblock %}
{% block content %}

    <div class="row">
        <div class="col-sm-6">
            <h4 class="alert-heading">Latest Projects</h4>
            <ul class="list-group list-group-flush">
                {% for latest_project in latest_projects %}
                    <li class="list-group-item"><a href="{% url 'project:detail' latest_project.slug %}">
                        {{ latest_project.title|truncatechars:35 }}</a></li>
                {% endfor %}
            </ul>
        </div>
        <div class="col-sm-6">
            <h4>Completed Projects</h4>
            <ul class="list-group list-group-flush">
                {% for completed_project in completed_projects %}
                    <li class="list-group-item"><a href="{% url 'project:detail' completed_project.slug %}">
                        {{ completed_project.title|truncatechars:'35' }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <div class="row">
        <div class="col-xl-12">
            <hr>
            <h4>Primary Projects</h4>
            <ul class="list-group list-group-flush">
                {% for primary_project in primary_projects %}
                    <li class="list-group-item"><a href="{% url 'project:detail' primary_project.slug %}">
                        {{ primary_project.title|truncatechars:'90' }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <!--  <div class="row">
         <div class="col-xl-6">
             <div class="card">
                 <div class="card-body">
                     <h5 class="card-title">Special title treatment</h5>
                     <p class="card-text">With supporting text below as a natural lead-in to additional
                         content.</p>
                     <a href="#" class="btn btn-primary">Go somewhere</a>
                 </div>
             </div>
         </div>
         <div class="col-xl-6">
             <div class="card">
                 <div class="card-body">
                     <h5 class="card-title">Special title treatment</h5>
                     <p class="card-text">With supporting text below as a natural lead-in to additional
                         content.</p>
                     <a href="#" class="btn btn-primary">Go somewhere</a>
                 </div>
             </div>
         </div>
     </div> -->

    <!--
    <button class="btn btn-primary" type="button" data-bs-toggle="offcanvas"
            data-bs-target="#offcanvasBottom" aria-controls="offcanvasBottom">Toggle bottom offcanvas
    </button>

    <div class="offcanvas offcanvas-bottom" tabindex="-1" id="offcanvasBottom"
         aria-labelledby="offcanvasBottomLabel">
        <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="offcanvasBottomLabel">Contact Information</h5>
            <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas"
                    aria-label="Close"></button>
        </div>
        <div class="offcanvas-body small">
            <p>Email: <a href="mailto:Contact.obeidarash@gmail.com"
                         target="_blank">Contact.obeidarash@gmail.com</a></p>
            <p>Whats App: <a href="https://wa.me/+989182789498" target="_blank">+989182789498</a></p>
            <p>Instagram: <a href="https://instagram.com/obeidarash" target="_blank">@obeidarash</a></p>
        </div>
    </div>
    -->

{% endblock %}

templates/project/project.html
{% extends "shared/MainReferences.html" %}
{% block keywords %}{{ project.tag.all|join:', ' }}{% endblock %}
{% block description %}{{ project.content }}{% endblock %}
{% block title %}{{ project.title }}{% endblock %}
{#{% block heading %}{{ project.title }}{% endblock %}#}

{% block content %}
    <div class="card text-center">
        <div class="card-header">
            {{ project.title }}
        </div>
        <div class="card-body">
            <h2 class="card-title">{{ project.title }}</h2>
            {{ project.content|safe }}
            {% if project.progress == 100 %}
                <div class="progress">
                    <div class="progress-bar bg-success" role="progressbar" style="width: 100%;" aria-valuenow="25"
                         aria-valuemin="0" aria-valuemax="100">Completed
                    </div>
                </div>
            {% else %}
                <div class="progress">
                    <div class="progress-bar" role="progressbar" style="width: {{ project.progress }}%;"
                         aria-valuenow="25"
                         aria-valuemin="0" aria-valuemax="100">{{ project.progress }}%
                    </div>
                </div>
            {% endif %}
        </div>
        <div class="card-footer text-muted">
            Tags:
            {% for tag in project.tag.all %}
                <a href="{% url 'project:tag' tag.slug %}">{{ tag.title }}</a>,
            {% endfor %}
            / Categories:
            {% for category in project.category.all %}
                <a href="{% url 'project:category' category.slug %}">{{ category.title }}</a>,
            {% endfor %}
            / Update:
            {{ project.create }}
        </div>
    </div>

{% endblock %}

templates/project/projects.html
{% extends 'shared/MainReferences.html' %}
{% block keywords %}{% endblock %}

{% block heading %}
        <h1>Projects</h1>
        <hr>
    {% endblock %}
{% block content %}

    {% include 'project/projects_component.html' with id=projects %}

    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                </li>
            {% endif %}
            {% for page in paginator.page_range %}
                {% if page == page_obj.next_page_number %}
                    <li class="page-item"><a class="page-link active" href="?page={{ page }}">{{ page }}</a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endblock %}

templates/project/projects_component.html
{% for project in projects %}
    <div class="card">
        <div class="card-body">
            <a href="{% url 'project:detail' project.slug %}"><h5 class="card-title">{{ project.title }}
                {% if project.primary == True %}
                    <span class="badge rounded-pill bg-primary">Primary</span>
                {% endif %}
            </h5></a>
            {#            <h6 class="card-subtitle mb-2 text-muted">web</h6>#}
            {#            {% if project.content %}#}
            {#                <p class="card-text">{{ project.content }}</p>#}
            {#            {% endif %}#}
            {% if project.progress == 100 %}
                <div class="progress">
                    <div class="progress-bar bg-success" role="progressbar" style="width: 100%;" aria-valuenow="25"
                         aria-valuemin="0" aria-valuemax="100">Completed
                    </div>
                </div>
            {% else %}
                <div class="progress">
                    <div class="progress-bar" role="progressbar" style="width: {{ project.progress }}%;"
                         aria-valuenow="25"
                         aria-valuemin="0" aria-valuemax="100">{{ project.progress }}%
                    </div>
                </div>
            {% endif %}
        </div>
        <div class="card-footer">
            <small class="text-muted">{{ project.update }}</small>
            <a href="admin/obeid_projects/project/{{ project.id }}/change/"
               class="btn btn-outline-dark btn-sm">Edit</a>
        </div>
    </div>
    <br>
{% endfor %}

templates/shared/FooterReferences.html
{% load static %}
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

templates/shared/HeaderReferences.html
{% load static %}
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

templates/shared/MainReferences.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{% block description %}{% endblock %}">
    <meta name="keywords" content="{% block keywords %}{% endblock %}">
    <meta name="author" content="Obeid Arash">
    <meta name="robots" content="index, follow">
    <meta name="language" content="English">
    {% include 'shared/HeaderReferences.html' %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col"></div>
        <div class="col-xl-6">

            {% include 'shared/Navigation.html' %}
            {% block heading %}{% endblock %}


            {% block content %}{% endblock %}

        </div>
        <div class="col"></div>
    </div> <!-- row -->
</div> <!-- container -->
{% include 'shared/FooterReferences.html' %}
</body>

</html>

templates/shared/Navigation.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ request.user.is_authenticated|yesno:'/admin, /admin/login/' }}">Obeid Arash</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% url 'home' as home %}
                    <a class="nav-link{% if request.path == home %} active{% endif %}" aria-current="page"
                       href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item">
                    {% url 'project:list'  as project %}
                    <a class="nav-link{% if request.path == project %} active{% endif %}"
                       href="{% url 'project:list' %}">Projects</a>
                </li>
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        {% url 'tools:youtube' as youtube %}
                        <a class="nav-link{% if request.path == youtube %} active{% endif %}"
                           href="{% url 'tools:youtube' %}">Youtube</a>
                    </li>
                {% endif %}
                {% if request.user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            Panel
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="/admin">Admin Area</a></li>
                            <li><a class="dropdown-item" href="#">Another action</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="/admin/logout">Exit</a></li>
                        </ul>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/tools/youtube.html
{% extends "shared/MainReferences.html" %}
{% block keywords %}{% endblock %}
{% block description %}{% endblock %}
{% block title %}YouTube{% endblock %}
{% block heading %}
    <h3>Youtube</h3>
    <hr>
{% endblock %}

{% block content %}
    <form action="" method="post" class="form-">
        {% csrf_token %}
        <div class="mb-3">
            <label for="{{ youtube.url.id_for_label }}">{{ youtube.url.label }}:</label>
            {{ youtube.errors }}
            {{ youtube.url }}
        </div>
        <button type="submit" class="btn btn-dark">Download</button>
    </form>

    {% if video %}
        <hr>
        <h4>{{ video.title }} </h4>
        <img src="{{ video.bigthumb }}" alt="{{ video.title }}" class="img-fluid align-middle">
        <h5>Videos:</h5>
        <table class="table">
            <thead>
            <tr>
                <th>Quality</th>
                <th>Size</th>
                <th>Format</th>
                <th>Type</th>
                <th>Download</th>
            </tr>
            </thead>
            <tbody>
            {% for s in videos %}
                <tr>
                    <td>{{ s.quality }}</td>
                    <td>{{ s.get_filesize|filesizeformat }}</td>
                    <td>{{ s.extension }}</td>
                    <td>{{ s.mediatype }}</td>
                    <td><a class="btn btn-info" href="{{ s.url }}">Download</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endif %}
{% endblock %}